//! The cargo backend for pmpx.
//!
//! Pure mapping: a verb plus its arguments in, one command out. It reads nothing, writes
//! nothing, and never looks at the environment -- everything the plugin is allowed to know
//! arrives in [`Context`], which the host filled in from files it already stat'd.

use std::ffi::OsString;

use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

struct Cargo;

impl PackageManager for Cargo {
    fn name(&self) -> &str {
        "cargo"
    }

    fn family(&self) -> Family {
        Family::RUST
    }

    fn command(
        &self,
        _ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        let spec = match verb {
            // cargo has no separate "install the dependencies" step -- building does it.
            // `fetch` is the closest thing: resolve and download, without building.
            Verb::Install if args.is_empty() => CommandSpec::new("cargo").arg("fetch"),
            Verb::Install => CommandSpec::new("cargo").arg("add").args(args.iter()),

            Verb::Remove => CommandSpec::new("cargo").arg("remove").args(args.iter()),

            // `cargo run` takes no script name, so a target here would be meaningless. Every
            // argument goes after `--`, where cargo stops looking for options of its own.
            Verb::Run => CommandSpec::new("cargo")
                .arg("run")
                .arg("--")
                .args(args.iter()),

            // `cargo build` takes only cargo's own options, so they go straight through.
            Verb::Build => CommandSpec::new("cargo").arg("build").args(args.iter()),

            // `cargo test` does not: it has a test harness behind it, and anything meant for
            // the harness has to sit after `--` or cargo rejects it as an unknown option.
            // `pmpx test -- --nocapture` is exactly that case.
            Verb::Test => CommandSpec::new("cargo")
                .arg("test")
                .arg("--")
                .args(args.iter()),

            // `cargo update` takes package specs as positional arguments, so no `-p` is needed.
            Verb::Update if args.is_empty() => CommandSpec::new("cargo").arg("update"),
            Verb::Update => CommandSpec::new("cargo").arg("update").args(args.iter()),

            // There is no `cargo exec`. Reporting it lets the host run the command itself,
            // which is the designed degradation -- better than inventing an equivalent.
            Verb::Exec => return Err(PluginError::unsupported_verb(verb)),
        };

        Ok(spec)
    }
}

/// The factory that the wrapper crate generated by crate-plugin-kit calls.
pub fn create() -> Box<dyn PackageManager> {
    Box::new(Cargo)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The context a host would hand over: the project root and the files it matched.
    ///
    /// Built through [`Context::builder`] rather than as a struct literal: the v3 context carries
    /// fields a plugin never sets (pins, reason, score, the declared files) and a lifetime, so the
    /// literal the v2 tests used no longer compiles -- and should not, since a plugin that fills
    /// those in by hand would be inventing what the host decides.
    fn ctx() -> Context<'static> {
        Context::builder()
            .project_root("/tmp/proj")
            .matched(["Cargo.lock", "Cargo.toml"])
            .build()
    }

    /// The exact argv the backend gets spawned with, program first.
    fn argv(verb: Verb, args: &[&str]) -> Vec<String> {
        let args: Vec<OsString> = args.iter().map(OsString::from).collect();
        let spec = Cargo.command(&ctx(), verb, &args).expect("should map");
        std::iter::once(spec.program.to_string_lossy().into_owned())
            .chain(spec.args.iter().map(|a| a.to_string_lossy().into_owned()))
            .collect()
    }

    #[test]
    fn install_without_arguments_fetches() {
        assert_eq!(argv(Verb::Install, &[]), ["cargo", "fetch"]);
    }

    #[test]
    fn install_with_arguments_adds_dependencies() {
        assert_eq!(
            argv(Verb::Install, &["serde", "anyhow"]),
            ["cargo", "add", "serde", "anyhow"]
        );
    }

    #[test]
    fn remove_removes_dependencies() {
        assert_eq!(argv(Verb::Remove, &["serde"]), ["cargo", "remove", "serde"]);
    }

    /// `cargo run` takes no script name, so every argument lands after `--`, where cargo stops
    /// looking for options of its own. This is the one mapping that is not a straight forward.
    #[test]
    fn run_puts_every_argument_after_a_double_dash() {
        assert_eq!(
            argv(Verb::Run, &["dev", "--port", "3000"]),
            ["cargo", "run", "--", "dev", "--port", "3000"]
        );
        assert_eq!(argv(Verb::Run, &[]), ["cargo", "run", "--"]);
    }

    #[test]
    fn build_forwards_its_arguments() {
        assert_eq!(
            argv(Verb::Build, &["--release"]),
            ["cargo", "build", "--release"]
        );
        assert_eq!(argv(Verb::Build, &[]), ["cargo", "build"]);
    }

    /// Same reason as `run`: `cargo test --nocapture` is rejected by cargo, the harness
    /// arguments have to come after `--`.
    #[test]
    fn test_puts_its_arguments_after_a_double_dash() {
        assert_eq!(
            argv(Verb::Test, &["--nocapture"]),
            ["cargo", "test", "--", "--nocapture"]
        );
        assert_eq!(argv(Verb::Test, &[]), ["cargo", "test", "--"]);
    }

    #[test]
    fn update_takes_package_specs_positionally() {
        assert_eq!(argv(Verb::Update, &[]), ["cargo", "update"]);
        assert_eq!(argv(Verb::Update, &["serde"]), ["cargo", "update", "serde"]);
    }

    /// There is no `cargo exec`. Reporting that is what makes the host fall back to running the
    /// command itself -- the designed degradation.
    #[test]
    fn exec_is_declared_unsupported() {
        let err = Cargo
            .command(&ctx(), Verb::Exec, &[OsString::from("ls")])
            .expect_err("exec must not be mapped onto a cargo subcommand");
        assert!(
            matches!(err, PluginError::UnsupportedVerb(_)),
            "expected UnsupportedVerb, got {err:?}"
        );
    }

    /// The text file the host reads before it loads any code must agree with the crate and the
    /// contract: `name` with `PackageManager::name()`, `family` with `PackageManager::family()`,
    /// `version` with this crate's version, and `abi` with the contract's major.
    ///
    /// No compiler checks these numbers, and the host trusts them -- a stale `abi` is how a plugin
    /// directory ends up "installed but refused". The check is deliberately a text one: a TOML parser
    /// would be this crate's only dependency, and the MSRV job builds `--all-targets`.
    #[test]
    fn the_manifest_agrees_with_the_crate_and_the_contract() {
        // Spaces dropped on both sides so the check does not care how the files are aligned.
        let manifest = std::fs::read_to_string("pmpx-plugin.toml")
            .expect("the manifest should be readable")
            .replace(' ', "");
        let cargo = std::fs::read_to_string("Cargo.toml")
            .expect("Cargo.toml should be readable")
            .replace(' ', "");

        let checked = [
            ("name", format!("name=\"{}\"", Cargo.name())),
            ("family", format!("family=\"{}\"", Cargo.family().as_str())),
            (
                "version",
                format!("version=\"{}\"", env!("CARGO_PKG_VERSION")),
            ),
            ("abi", format!("abi={}", pmpx_plugin::abi::PMPX_ABI_MAJOR)),
        ];

        for (what, wanted) in checked {
            assert!(
                manifest.contains(&wanted),
                "the manifest must declare `{wanted}` for {what}; it says:\n{manifest}"
            );

            if what == "version" {
                assert!(
                    cargo.contains(&wanted),
                    "Cargo.toml must declare `{wanted}` too, or the store reports a version this crate does not have"
                );
            }
        }
    }
}
